### ISSUE TITLE
v1 buil-target.mk

### ISSUE THREAD

**Issue by mandidayat** [Rhoban/Metabot#13]
why if i uncoment CFLAGS += -DDXL_VERSION_1 and i make is error

out put error 
=====================================================
Maple/LibRhoban/dxl.cpp: In function 'void dxl_init(int, bool)':
Maple/LibRhoban/dxl.cpp:322:37: error: 'DXL_WHEEL' was not declared in this scope
         dxl_set_mode(DXL_BROADCAST, DXL_WHEEL);
                                     ^
Maple/LibRhoban/dxl.cpp: In function 'bool dxl_sync_read(ui8*, int, ui8, ui8, ui8*)':
Maple/LibRhoban/dxl.cpp:694:5: error: return-statement with no value, in function returning 'bool' [-fpermissive]
     return;
     ^
Maple/LibRhoban/dxl.cpp: In function 'void dxl_disable_all()':
Maple/LibRhoban/dxl.cpp:755:35: error: 'DXL_TORQUE_EN' was not declared in this scope
     dxl_write_word(DXL_BROADCAST, DXL_TORQUE_EN, 0);
                                   ^
Maple/LibRhoban/dxl.cpp: In function 'void dxl_set_mode(int, int)':
Maple/LibRhoban/dxl.cpp:857:24: error: 'DXL_MODE' was not declared in this scope
     dxl_write_byte(id, DXL_MODE, mode);
                        ^
build-targets.mk:18: recipe for target 'build/./Maple/LibRhoban/dxl.o' failed
make: *** [build/./Maple/LibRhoban/dxl.o] Error 1

regard

**Comment by Gregwar** [comment]
Hello,

I updated `Maple` to add this missing registers, can you pull it and try again?
