### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by leelegend94** [Rhoban/Metabot#14]
Compiling failed while "[LD]        maple_mini.elf" with many errors like the followings:

build/./Maple/LibRhoban/commands.o: In function `start()':
/home/parallels/Workspace/rl/metabot_project/firmware/src/Maple/LibRhoban/commands.cpp:69: undefined reference to `dxl_flush()'
...

**Comment by AndreasFWallin** [comment]
I have the same problem, both on Windows and Linux

**Comment by leelegend94** [comment]
There are 2 source file not compiled by default, which is however crucial for Metabot...
Fix:
in firmware/src/Maple/LibRhoban/rules.mk
1. "ENABLE_DXL := no"  --> "ENABLE_DXL := yes"
2. uncomment "#cppSRCS_$(d) += servos.cpp"
3. have fun
