### ISSUE TITLE
bug de simulateur

### ISSUE THREAD

**Issue by theking391** [Rhoban/Metabot#2]
le simulateur ne me permet pas d'effectuer un rectangle de 1200 mm sur 2200mm . Le robot ne respecte pas les angles imposés il dévie de sa trajectoire a partir du second coté ( le 1er 22000mm)

**Comment by Gregwar** [comment]
Bonjour,
Les trajectoires simulées ne sont en effet pas parfaites, mais cela sera encore pire dans la réalité
Le robot va glisser sur le sol, les moteurs auront du retard etc.

**Comment by theking391** [comment]
c'est embêtant car je dois participer a un concours et si je ne peux pas m'entrainer sur le logiciel ni sur le robot cela me désavantage grandement. Auriez-vous une astuce/idée de comment résoudre ce problème ??

**Comment by Gregwar** [comment]
Vous ne devez de toutes façon pas miser sur le fait qur les trajectoires seront suivies parfaitement
Essayez de fermer les yeux et de faire un parcours: c'est le même probleproblème

**Comment by theking391** [comment]
ah. alors on va essayer de se débrouiller merci pour les infos:)

**Comment by Gregwar** [comment]
Avez vous vu la vidéo de tutoriel?

**Comment by ghost** [comment]
Bonjour, 
Je suis un ami de theking391 et nous travaillons ensemble sur ce projet et je vous confirme que nous avons regarder la vidéo de tutoriel mais même en suivant toutes les étapes notre carré ou rectangle (de n'importe quelle taille d'ailleurs) ne respecte pas les angles et les rend inférieurs à 90°.
 Merci à vous :)

**Comment by Gregwar** [comment]
Ce qu'il faut savoir, c'est que le robot fait des mouvements qui devraient _théoriquement_ donner 90° ou tant de milimètres, mais dans la pratique, un grand nombre de choses peuvent faire que ça ne marche pas
Il est impossible de faire des "parcours" précis sans capteurs (dans une prochaine version, le robot sera équipé de capteurs de distances) ni aucun retour d'information
C'est un peu comme si vous essayiez de faire un parcours les yeux fermés

**Comment by ghost** [comment]
Merci à vous pour votre suivi de notre problème. Pour information, nous travaillons avec Madame Blanc pour le Robot Maker's Day. 
A bientôt. :)
